### ISSUE TITLE
Choix du sujet, utilité sociale et effets de la numérisation

### ISSUE THREAD

**Issue by benel** [UTT-GL03/FAMILINK#1]
Merci pour votre texte @DanHaziel et @TsukiSo.

J'ai un petit doute concernant vos données chiffrées : 
- [x] "4,3 Milliards" : quand on regarde votre source, on est au-delà de 5 Milliards, non ? Ou bien avez-vous volontairement soustrait certaines lignes ?

Il y a de petites coquilles : 
- [x] "choix du sujet :" (il ne faut pas de signe de ponctuation à la fin d'un titre de section),
- [x] liste : pensez bien à mettre un point à la fin du dernier item, et une virgule à la fin des autres items,
- [x] il y a un petit problème de construction dans votre dernière phrase : "se porter" se construit effectivement avec "sur" mais pas "respecter".

Merci d'avance.

**Comment by benel** [comment]
Merci pour toutes ces corrections @TsukiSo et @DanHaziel.

Attention, il y a :
- [x] un nouveau [petit problème de syntaxe Markdown](https://github.com/UTT-GL03/FAMILINK#:~:text=Ce%20sont%20principalement%20sur%20ces%20quatre%20points%20que%20notre%20travail%20portera%2C%20et%20nous%20veillerons%20%C3%A0%20ce%20que%20notre%20prototypage%20les%20respecte.Sc%C3%A9narios%20d%27usage%20et%20impacts) (lien vers un fragment de texte à ouvrir avec Chrome ou Firefox) (par ailleurs la phrase est bizarre...),
- [x] une coquille ("âtre"),
- [x] une majuscule sans raison ("utilisateurs : L'entame").

**Comment by benel** [comment]
@DanHaziel @TsukiSo Avez-vous trouvé le poids carbone d'une lettre (selon différents cas) ?

**Comment by TsukiSo** [comment]
J'ai eu pas mal de soucis pour trouver des chiffres concrets, mais dans cette article (https://www.linkedin.com/pulse/mail-versus-courrier-papier-qui-est-le-bon-élève-jean-pierre-guéno/) il est dit que "Une lettre verte envoyée par La Poste de Paris à Marseille consomme l’équivalent de 21,6 g de CO2".

**Comment by benel** [comment]
Merci @TsukiSo (et @DanHaziel )
C'est intéressant ce que vous avez trouvé sur l'impact d'une lettre classique : pour une fois, le gain est vraiment très significatif (ce qui n'empêche pas de possibles effets rebonds)..
N'oubliez pas d'ajouter cette information dans votre README.
