### ISSUE TITLE
Comparer

### ISSUE THREAD

**Issue by benel** [UTT-GL03/FAMILINK#6]

**Comment by benel** [comment]
@TsukiSo @DanHaziel 

> Nous avons décidé de comparer l'impact des scénarios sur l'application web de la messagerie Discord. 

Comparer les scénarios ? Même si c'est intéressant ce n'est pas strictement ce qui est demandé... Le badge à valider s'appelle "**Comparer l'impact écologique estimé d'applications Web du même type**". Pour que je puisse vous le valider, il en faut au moins 2.

Quel autre concurrent allez-vous choisir ? Pour quelles raisons ?

**Comment by TsukiSo** [comment]
Nous allons utiliser Whatsapp Web car c'est l'application qui ressemble le plus à l'application que nous sommes en train de développer. A noter que les pages de l'application WhatsApp web ne sont pas du tout indexées.
